apiVersion: v1
kind: Pod
metadata:
  name: env
spec:
  containers:
  - name: ngin
    image: nginx
    env:
    - name: course
      value: docker
    - name: trainer
      value: siva
    - name: duration
      value: 25hrs
    - name: DB_HOST
      value: db.admin.com
    - name: username
      value: sivakumar